version: '3.7'
services:
  backend:
    container_name: server.dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ./:/usr/src/app
      - /app/node_modules
    ports:
      - 3000:3000
